# Generated by Django 3.2.20 on 2023-09-05 12:40

from django.db import migrations, models
import recipemanager.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipemanager', '0002_accounts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_number',
            field=models.CharField(default=recipemanager.models.generate_account_number, max_length=20, unique=True),
        ),
    ]
